### ISSUE TITLE
[SALARY_COMPETITION](AMIN ALSABAGH)

### ISSUE THREAD

**Issue by aminmadrileno** [Ironhack-Data-Madrid-Enero-2023/SALARY_COMPETITION#34]
https://github.com/aminmadrileno/ML-Project-Salaries/tree/main

**Comment by fjgarciaes** [comment]
Good job Amin but try to improve( or do) the readme, please. Because this is the last feedback before the final project I want to congratulate you for all the hard work you've put into this bootcamp I know it was more difficult for you because of the Spanish but you didn't let that take you down and you've worked very hard (almost)everyday to do the labs the best way possible and challenge yourself everyday so congratulations and good luck with the final project :)
